services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: db-gestao-tarefas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao-tarefas
    ports:
      - "5432:5432"
    volumes:
      - esig_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  esig_postgres_data: